ProtocolConfiguration:
  ChainID: 53
  MaxTraceableBlocks: 2102400
  InitialGASSupply: 52000000
  KeepOnlyLatestState: false
  MaxBlockSize: 262144
  MaxBlockGas: 90000000000
  MaxTransactionsPerBlock: 512
  SecondsPerBlock: 15
  MemPoolSize: 50000
  StandbyValidators:
    - 02a958dcbdda5fe1176fb6c76635f37ddccc50dd138496708007821db8c80f3935
  SeedList:
    - seed1.ngd.network:10333
  VerifyBlocks: true
  VerifyTransactions: false
  MainStandbyStateValidatorsScriptHash: ""
  BridgeContractId: 1

ApplicationConfiguration:
  # LogPath could be set up in case you need stdout logs to some proper file.
  DBConfiguration:
    Type: "leveldb" #other options: 'inmemory','boltdb'
    # DB type options. Uncomment those you need in case you want to switch DB type.
    LevelDBOptions:
      DataDirectoryPath: "./chains/mainnet"
  #    BoltDBOptions:
  #      FilePath: "./chains/mainnet.bolt"
  #  Uncomment in order to set up custom address for node.
  #  Address: 127.0.0.1
  NodePort: 10333
  Relay: true
  DialTimeout: 3
  ProtoTickInterval: 2
  PingInterval: 30
  PingTimeout: 90
  MaxPeers: 100
  AttemptConnPeers: 10
  MinPeers: 1
  UnlockWallet:
    Path: ""
    Password: ""
  StateRoot:
    Enabled: false
    UnlockWallet:
      Path: ""
      Password: ""
  RPC:
    Enabled: true
    MaxGasInvoke: 15
    EnableCORSWorkaround: false
    Port: 10332
    TLSConfig:
      Enabled: false
      Port: 10301
      CertFile: serv.crt
      KeyFile: serv.key
  Prometheus:
    Enabled: true
    Port: 2112
  Pprof:
    Enabled: false
    Port: 2113
